LABELS = [
    "The Great Wall of China",
    "The Mona Lisa",
    "airplane",
    "angel",
    "arm",
    "beach",
    "bear",
    "bed",
    "brain",
    "bridge",
    "broom",
    "bulldozer",
    "calculator",
    "calendar",
    "campfire",
    "cannon",
    "castle",
    "church",
    "coffee cup",
    "crab",
    "crocodile",
    "cruise ship",
    "dolphin",
    "dragon",
    "elbow",
    "elephant",
    "feather",
    "fence",
    "fire hydrant",
    "fireplace",
    "firetruck",
    "flip flops",
    "flying saucer",
    "garden hose",
    "golf club",
    "guitar",
    "hamburger",
    "helicopter",
    "hockey puck",
    "horse",
    "hospital",
    "hot air balloon",
    "hot dog",
    "house plant",
    "ice cream",
    "jail",
    "kangaroo",
    "ladder",
    "lantern",
    "light bulb",
    "lighthouse",
    "lion",
    "mailbox",
    "megaphone",
    "microphone",
    "microwave",
    "mountain",
    "necklace",
    "ocean",
    "octopus",
    "paint can",
    "paintbrush",
    "palm tree",
    "parachute",
    "piano",
    "picture frame",
    "police car",
    "pond",
    "pool",
    "radio",
    "roller coaster",
    "sailboat",
    "sandwich",
    "screwdriver",
    "skateboard",
    "skull",
    "skyscraper",
    "snail",
    "snowman",
    "spider",
    "streetlight",
    "submarine",
    "suitcase",
    "teddy-bear",
    "television",
    "tent",
    "toaster",
    "toothbrush",
    "toothpaste",
    "tractor",
    "traffic light",
    "train",
    "tree",
    "truck",
    "umbrella",
    "washing machine",
    "waterslide",
    "windmill",
    "wine bottle",
    "wristwatch",
]

LABELS_TO_INDEX = {label: index for index, label in enumerate(LABELS)}
INDEX_TO_LABELS = {index: label for index, label in enumerate(LABELS)}
